from pathlib import Path
import json
root=Path('math-tutor');course=root/'courses/levels-4a-4b-5';manifest=json.loads((course/'manifest.json').read_text(encoding='utf-8'))
for u in manifest['units']:
 for l in u['lessons']:
  l['formulas']=[f.replace('bar(x)','overline(x)') for f in l['formulas']]
  l['practice']=json.loads((root/l['lesson_path']/'practice.json').read_text(encoding='utf-8'))['batches']
 u['test']=json.loads((course/u['id']/'tests/form-A.json').read_text(encoding='utf-8'))['items']
# Learner-facing embedded data contains prompts only, never keys.
data=json.dumps(manifest,ensure_ascii=False).replace('</','<\\/')
page='''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Math — visual lessons</title>
<style>
:root{color-scheme:dark;font-family:Segoe UI,system-ui,sans-serif;background:#0b0e12;color:#e8edf4}*{box-sizing:border-box}body{margin:0}header{padding:24px 5vw;border-bottom:1px solid #27303b;display:flex;gap:20px;justify-content:space-between;align-items:center}a{color:#7bd7ed}h1{font-size:22px;font-weight:500;margin:0}small,.muted{color:#acb8c6}main{max-width:1440px;margin:auto;padding:28px;display:grid;grid-template-columns:255px minmax(0,1fr);gap:30px}nav{display:flex;flex-direction:column;gap:8px}button,select{font:inherit;background:#171e27;color:#e8edf4;border:1px solid #374354;border-radius:7px;padding:11px;cursor:pointer}button:hover,button:focus-visible{border-color:#7bd7ed}button[aria-current=true]{background:#15343d;border-color:#7bd7ed}nav button{text-align:left;font-size:14px;line-height:1.5}select{width:100%;margin-bottom:12px}video{display:block;width:100%;max-height:66vh;background:#000}h2{font-weight:500;font-size:24px;line-height:1.3}p{line-height:1.65}#questions{padding-left:25px;line-height:1.8}#questions li{margin:18px 0;padding-left:8px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin:20px 0}.practice{margin-top:25px;border-top:1px solid #27303b;padding-top:8px}button:disabled{opacity:.45;cursor:default}.links{display:flex;gap:20px;flex-wrap:wrap;margin-top:15px}#testnote{border-left:2px solid #7bd7ed;padding-left:14px}#status{min-height:24px;color:#7bd7ed}@media(max-width:800px){main{display:block;padding:18px}nav{margin-bottom:24px;max-height:230px;overflow:auto}header{align-items:flex-start}h1{font-size:18px}}
</style>
<header><h1>Math · visual lessons</h1><small>Watch. Try three. Ask questions.</small></header>
<main><aside><label for="unit">Choose a unit</label><select id="unit"></select><nav id="lessons" aria-label="Lessons"></nav></aside><article><p id="eyebrow" class="muted"></p><h2 id="title"></h2><p id="objective"></p><video id="video" controls preload="metadata" playsinline></video><div class="links"><a id="transcript">Transcript</a><a id="guide">Lesson guide</a><a href="assessment_policy.md">How progression works</a></div><section class="practice"><h2 id="batchTitle"></h2><p id="help"></p><p id="testnote" hidden></p><ol id="questions"></ol><div class="actions"><button id="previous">Previous set</button><button id="next">Next three</button><button id="copy">Copy these questions</button></div><p id="status" role="status"></p><p class="muted">Send your numbered answers and working to the tutor. This player does not grade answers or mark a topic passed.</p></section><div class="actions"><button id="nextLesson">Next lesson</button><button id="test">Start unit test</button></div></article></main>
<script>
const DATA=__DATA__;let ui=0,li=0,batch=0,testing=false;const el=id=>document.getElementById(id);const unit=()=>DATA.units[ui];const lesson=()=>unit().lessons[li];
function batches(){if(!testing)return lesson().practice;const q=unit().test;return Array.from({length:Math.ceil(q.length/3)},(_,i)=>q.slice(i*3,i*3+3))}
function questionView(){const bs=batches();el('batchTitle').textContent=(testing?'Unit test':'Practice')+' · set '+(batch+1)+' of '+bs.length;el('help').textContent=testing?'Work independently and show your reasoning. Ask if wording is unclear.':'Try these three problems. Ask the tutor for help whenever you get stuck.';el('testnote').hidden=!testing;el('testnote').textContent='Mathematical help pauses independent scoring for that item. After teaching, the tutor will use a fresh question. Readiness requires 80% plus topic coverage and resolved prerequisite gaps.';el('questions').replaceChildren(...bs[batch].map(q=>{const item=document.createElement('li');item.textContent=q.id+': '+q.prompt;return item}));el('previous').disabled=batch===0;el('next').disabled=batch===bs.length-1;el('status').textContent='';el('test').textContent=testing?'Return to practice':'Start unit test'}
function render(){const l=lesson();el('eyebrow').textContent='LEVEL '+unit().id.toUpperCase()+' / '+unit().title+' / LESSON '+(li+1)+' OF '+unit().lessons.length;el('title').textContent=l.title;el('objective').textContent=l.objective;el('video').src='../../'+l.video_path+'/final.mp4';el('video').poster='qa/'+l.id+'-0.jpg';el('transcript').href='../../'+l.video_path+'/narration.txt';el('guide').href=l.lesson_path.split('levels-4a-4b-5/')[1]+'/lesson.md';el('nextLesson').disabled=li===unit().lessons.length-1;el('lessons').replaceChildren(...unit().lessons.map((x,i)=>{const b=document.createElement('button');b.textContent=String(i+1).padStart(2,'0')+' · '+x.title;b.setAttribute('aria-current',i===li?'true':'false');b.onclick=()=>{li=i;batch=0;testing=false;render()};return b}));questionView()}
DATA.units.forEach((u,i)=>{const o=document.createElement('option');o.value=i;o.textContent=u.id.toUpperCase()+' — '+u.title;el('unit').append(o)});el('unit').onchange=e=>{ui=Number(e.target.value);li=0;batch=0;testing=false;render()};el('previous').onclick=()=>{batch--;questionView()};el('next').onclick=()=>{batch++;questionView()};el('nextLesson').onclick=()=>{li++;batch=0;testing=false;render()};el('test').onclick=()=>{testing=!testing;batch=0;el('video').pause();questionView()};el('copy').onclick=async()=>{const s=batches()[batch].map(q=>q.id+': '+q.prompt).join('\n\n');try{await navigator.clipboard.writeText(s);el('status').textContent='Copied. Paste into the tutor with your work.'}catch{el('status').textContent='Select the question text above and copy it manually.'}};render();
</script></html>'''
page=page.replace('__DATA__',data).replace(".join('\n\n')", ".join('\\n\\n')")
(course/'index.html').write_text(page,encoding='utf-8');print('Player built: 24 lessons, questions only')
