import {autosave,isDraftSave} from './autosave.js';
import {mountPurposePaths} from './purpose-paths.js';
import {renderAnswerVisual,fallbackVisual} from './answer-visuals.js';
import {mountAILearning} from './ai-learning.js';
import {cardArt} from './card-art.js';
import {createLearningPathUI,draftSaver} from './learning-path.js';
import {createProjectJourneysUI} from './project-journeys.js';
import {enhanceMathInputs} from './math-input.js';
import {mountLab,labFor} from './labs.js';
import {createLearningUI} from './learning.js';
import {mountReasoning} from './reasoning.js';
import {createVideoCatalogUI} from './video-catalog.js';
import {createPlacementUI} from './placement.js';
import {createStudioUI} from './studio.js';
import {createMixedReviewUI} from './mixed-review.js';
import {createFeedbackUI} from './feedback.js';
import {createTourUI} from './tour.js';
import {mountPlayground} from './playground.js';
import {createCalculator} from './calculator.js?v=7';
import {createLessonCoach} from './lesson-coach.js';
import {mountSkillTree} from './skill-tree.js';
import {loadMissionContent,mountMission,mountMissionDirectory} from './lesson-missions.js';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let catalog,progress,lessonMap={},routeVersion=0,disposeLab=null,currentActivity=null,activityBatch=0,saveTimer,homeworkView=0;
let boundProfileId=null,missionContent=null,lessonContext=null,learningState={},stopMathInput=null;
const learning=createLearningUI({api,esc,toast,copy,refresh:()=>render()});
const learningPath=createLearningPathUI({api,esc,toast,topic:id=>learning.topic(id),onCoach:()=>coach.open()});
const projects=createProjectJourneysUI({api,esc,toast,missions:()=>missionContent,onContext:id=>setLessonTools('watch',id,'project')});
const placement=createPlacementUI({api,esc,getProfile:()=>boundProfileId});
const videos=createVideoCatalogUI({api,esc,toast,copy,learning,legacyLesson:id=>lessonMap[id],mountLegacyPractice:id=>begin(id,'practice'),mountLegacyHomework:l=>homeworkPanel(l),onCalculator:()=>openCalculator(),onHelp:()=>coach.open(),mountApplication:(host,id)=>mountLessonMission(host,id),mountScaffold:(host,id)=>learningPath.mountScaffold(host,id),mountTools:(host,id,tab)=>learningPath.mountTools(host,id,tab),warmup:()=>learningPath.homeLink()});
const studio=createStudioUI({api,esc,toast,copy});
const mixedReview=createMixedReviewUI({api,esc,toast});
const feedbackDesk=createFeedbackUI({api,esc,toast,copy});
const tour=createTourUI({api,esc});
const coach=createLessonCoach({api,esc});
const calculator=createCalculator({esc,onSupport:event=>api('calculator/support',{topic_id:event.topicId||null,kind:event.kind},event.profileId)});
function openCalculator(){coach.close();calculator.open();}
function mountLessonMission(host,topicId){
 const profile=boundProfileId,saved=progress.topics?.[topicId]?.mission||{},design=learningState.mission_designs?.[topicId]||{};
 let revision=Math.max(Date.now(),saved.revision||0);
 const saver=draftSaver({api,profile,path:'learning/mission-design',base:{topic_id:topicId},initialRevision:design.revision,status:message=>{const el=host.querySelector('[data-calc-status]');if(host.isConnected&&el&&el.textContent!==message)el.textContent=message;},onSaved:(s,n)=>{if(profile!==boundProfileId)return;learningState.mission_designs??={};learningState.mission_designs[topicId]={draft:s.draft,revision:n};},onError:e=>toast(e.message)});
 let stopped=false,stop=()=>{};host.innerHTML='<p class="mission-loading">Opening the application…</p>';
 api('topic/help',{topic_id:topicId},profile).then(()=>{if(stopped)return;stop=mountMission(host,{topicId,esc,api,content:missionContent,initialDraft:saved,initialDesign:design.draft,onDesign:draft=>{saver.write({draft});return draft.calculation?.ran?saver.flush():undefined;},onSupport:()=>api('topic/help',{topic_id:topicId},profile),onDraft:draft=>{const sent=++revision;progress.topics[topicId]??={};progress.topics[topicId].mission={prediction:draft.prediction,explanation:draft.explanation,revision:sent};return api('topic/mission',{topic_id:topicId,prediction:draft.prediction,explanation:draft.explanation,revision:sent},profile).then(()=>{if(host.isConnected&&sent===revision){const note=host.querySelector('.mission-save-note');if(note)note.textContent='✓ Saved with this lesson · also in My homework';}});}});}).catch(error=>{if(!stopped)host.innerHTML='<p class="error">'+esc(error.message)+'</p>';});
 const unload=()=>saver.flushImmediate().catch(()=>{});window.addEventListener('pagehide',unload);
 return()=>{stopped=true;window.removeEventListener('pagehide',unload);stop();saver.flush().catch(()=>{});};
}
function purposePathCard(){return `<a class="purpose-home-entry" href="#applications"><span class="purpose-home-icon" aria-hidden="true">⌁</span><div><h2>What do you want to build?</h2><p>Physics, engineering, architecture, finance, or AI.</p></div><strong>Choose a path →</strong></a>`;}

function purposeHomework(){const names={physics:'Physics',mechanical:'Mechanical engineering',electrical:'Electrical engineering',architecture:'Architecture & civil engineering',finance:'Finance'};const fields=Object.keys(learningState.purpose_paths||{}).filter(id=>names[id]);return fields.length?'<section class="saved-learning-notes"><h2>My applied experiments</h2><div class="lesson-list">'+fields.map(id=>'<a class="topic-node" href="#applications/'+id+'"><span class="topic-description"><strong>'+names[id]+'</strong><small>Continue my saved controls and notes</small></span><span>Open →</span></a>').join('')+'</div></section>':'';}

function missionHomework(){const ids=[...new Set([...Object.keys(progress.topics||{}),...Object.keys(learningState.mission_designs||{})])].filter(id=>{const note=progress.topics?.[id]?.mission,design=learningState.mission_designs?.[id]?.draft;return note?.prediction?.trim()||note?.explanation?.trim()||design?.calculation?.answer?.trim()||design?.activity?.answer?.trim();});return ids.length?'<div class="section-title"><h2>My lesson applications</h2></div><div class="lesson-list">'+ids.map(id=>`<a class="topic-node" href="#mission/${id}"><span class="topic-description"><strong>${esc(learning.topic(id)?.title||id)}</strong><small>Continue my saved notes & experiment</small></span><span>Open →</span></a>`).join('')+'</div>':'';}
function visibleLessonWork(){
 const visible=el=>el.checkVisibility?el.checkVisibility():el.getClientRects().length>0;
 const work=Array.from(document.querySelectorAll('.unified-lesson .question')).filter(visible).map(q=>{
  const prompt=q.querySelector('.question-title')?.textContent?.trim()||'';
  const answers=Array.from(q.querySelectorAll('input:not([type=radio]),input[type=radio]:checked,textarea')).map(f=>f.value).filter(Boolean);
  const shown=Array.from(q.querySelectorAll('p')).find(p=>p.textContent.startsWith('Your answer:'));
  if(!answers.length&&shown)answers.push(shown.textContent.slice(12).trim());
  return answers.length?prompt+'\nMy work: '+answers.join('\n'):'';
 }).filter(Boolean);
 document.querySelectorAll('.lesson-mission [data-draft]').forEach(field=>{if(visible(field)&&field.value.trim())work.push((field.labels?.[0]?.textContent||'Mission note')+'\nMy work: '+field.value);});
 document.querySelectorAll('.step-line-input,.step-workspace textarea,.project-response,.ai-stage textarea,.calculation-answer').forEach(field=>{if(visible(field)&&field.value.trim())work.push('My written work: '+field.value);});
 const aiStage=document.querySelector('.ai-stage');if(aiStage)work.push('AI model context: '+(aiStage.querySelector('h1,h2')?.textContent||'')+'\n'+(aiStage.querySelector('[aria-label="Live numerical equation"]')?.textContent||''));
 return work.join('\n\n').slice(0,6000);
}
function setLessonTools(page,id,tab){const topicId=page==='watch'||page==='topic'||page==='mission'?id:page==='lesson'?learning.topicForLegacy(id):null;const topic=topicId?learning.topic(topicId):null;const independentCheck=(['topic','lesson'].includes(page)&&tab==='check')||['placement','unit-test','bridge','review','session'].includes(page);lessonContext={topicId,title:topic?.title||'Math calculator',profileId:boundProfileId,independentCheck,practiceHref:topicId?'#watch/'+topicId+'/practice':'#videos',pageKey:page+'/'+id+'/'+tab,getWork:visibleLessonWork,onReturnToPractice:()=>{location.hash=topicId?'#watch/'+topicId+'/practice':'#videos';}};calculator.setContext(lessonContext);coach.setContext(topic?lessonContext:null);document.querySelectorAll('input,textarea').forEach(field=>field.dispatchEvent(new Event('math-input-context')));}
document.addEventListener('click',e=>{if(e.target.closest?.('#lc-launcher'))calculator.close();});
const palette={ '4a':{accent:'#638558',pale:'#eaf0df',short:'Geometry',description:'See the relationships between shapes, lengths, and space.'},'4b':{accent:'#aa8650',pale:'#f5eddb',short:'Statistics',description:'Find patterns in data. Reason clearly about uncertainty.'},'5':{accent:'#7c82ae',pale:'#eaecf6',short:'Algebra II',description:'Connect expressions, graphs, and the way functions behave.'}};
function api(path,data,requestProfileId=boundProfileId){
 return autosave.track(path,data,requestProfileId,async(snapshot,profile)=>{
  const headers=snapshot===undefined?{}:{'Content-Type':'application/json',...(profile?{'X-Catalyst-Profile':profile}:{})};
  const body=snapshot===undefined?undefined:JSON.stringify(snapshot);
  const keepalive=snapshot!==undefined&&(isDraftSave(path,snapshot)||['placement/draft','feedback/save','video','tour/progress'].includes(path))&&new TextEncoder().encode(body).length<60000;
  const res=await fetch('/api/'+path,snapshot===undefined?{}:{method:'POST',headers,body,keepalive});
  const value=await res.json();
  if(!res.ok){const error=Error(value.error||'Could not complete that request.');error.status=res.status;throw error;}
  const returned=value.profile_id||value.profile?.id||(path==='export'&&value.progress?.profile_id);
  if(returned&&boundProfileId&&returned!==boundProfileId||path==='profiles'&&boundProfileId&&value.current?.id!==boundProfileId){const error=Error('The learning space changed in another tab. Copy any unsaved work, then reload this page.');error.status=409;throw error;}
  if(['profiles','profiles/create','profiles/select'].includes(path)&&value.current?.id){boundProfileId=value.current.id;autosave.status();}
  return value;
 });
}
autosave.start({profile:()=>boundProfileId,report:({state,savedAt,error})=>{
 const el=$('#global-save-status');if(!el)return;el.dataset.state=state;
 el.textContent=state==='error'?'Not saved':state==='saving'?'Saving…':state==='saved'?'✓ Saved':'Autosave on';
 el.title=state==='error'?'Could not save. Keep this page open. '+error:state==='saved'?'Saved on this computer at '+new Date(savedAt).toLocaleTimeString()+'. Changes save as you work; a safety check runs every minute.':'Changes save as you work; a safety check runs every minute.';
}});

function toast(message){const el=$('#toast');el.textContent=message;el.hidden=false;setTimeout(()=>el.hidden=true,4000)}
const passed=id=>!!progress.lessons[id]?.check_passed;
const count=u=>u.lessons.filter(l=>passed(l.id)).length;
const thumb=l=>'/thumbnails/'+l.id+'-0.jpg';
const unit=id=>catalog.units.find(u=>u.id===id);
const next=u=>u.lessons.find(l=>!passed(l.id))||u.lessons[u.lessons.length-1];
function art(id){
 const start='<svg viewBox="0 0 300 170" aria-hidden="true" fill="none">';
 if(id==='4a')return start+'<circle cx="165" cy="88" r="57" stroke="#9aaf80" stroke-width="1" stroke-dasharray="3 5"/><path d="M90 139 L205 139 L151 33Z" fill="#d3dfc0" fill-opacity=".55" stroke="#68845b" stroke-width="2"/><path d="M151 33V139" stroke="#a7b98e" stroke-dasharray="4 4"/><path d="M151 129H161V139" stroke="#8ba476"/><circle cx="151" cy="33" r="5" fill="#f2f6e9" stroke="#68845b" stroke-width="2"/><circle cx="90" cy="139" r="4" fill="#68845b"/><circle cx="205" cy="139" r="4" fill="#68845b"/></svg>';
 if(id==='4b')return start+'<path d="M63 143H246" stroke="#d6c297"/><rect x="80" y="105" width="22" height="38" rx="3" fill="#ddcca7"/><rect x="112" y="69" width="22" height="74" rx="3" fill="#ccb27e"/><rect x="144" y="39" width="22" height="104" rx="3" fill="#b8995e"/><rect x="176" y="78" width="22" height="65" rx="3" fill="#ccb27e"/><rect x="208" y="117" width="22" height="26" rx="3" fill="#ddcca7"/><path d="M58 130C94 130 118 15 156 16C193 17 202 125 255 132" stroke="#aa8650" stroke-width="2"/></svg>';
 return start+'<path d="M55 116H258M152 18V153" stroke="#c7c9df"/><path d="M75 28 Q153 233 230 28" stroke="#7b83b2" stroke-width="2.5"/><path d="M71 145L238 38" stroke="#b4bad7" stroke-dasharray="4 4"/><circle cx="152" cy="131" r="5" fill="#f4f4fa" stroke="#7b83b2" stroke-width="2"/><circle cx="114" cy="104" r="3" fill="#7b83b2"/><circle cx="190" cy="104" r="3" fill="#7b83b2"/></svg>';
}
function courseCard(u){const p=palette[u.id],done=count(u),l=next(u);return `<section class="card" style="--accent:${p.accent};--pale:${p.pale}"><a href="#course/${u.id}"><div class="course-art"><span class="unit-tag">LEVEL ${u.id.toUpperCase()}</span>${cardArt({id:u.id==='4a'?'geometry':u.id==='4b'?'statistics-basics':'algebra-2',kind:'course',title:u.title})}</div></a><div class="course-info"><h3><a href="#course/${u.id}">${esc(u.title)}</a></h3><p>${p.description}</p><div class="progress-label"><span>${done} of ${u.lessons.length} lesson checks passed</span><span>${Math.round(done/u.lessons.length*100)}%</span></div><div class="progressbar"><span style="width:${done/u.lessons.length*100}%"></span></div><div class="course-bottom"><span>${u.lessons.length} lessons · ${Math.round(u.lessons.reduce((a,l)=>a+l.duration_seconds,0)/60)} min of video</span><a href="#lesson/${l.id}/video">${done?'Continue':'Explore course'} →</a></div></div></section>`}
function home(){return videos.home(progress)}
function row(l){const status=passed(l.id)?'<span class="pill done">✓ Check passed</span>':progress.unlocked[l.id]?'<span class="pill">Ready to begin</span>':'<span class="pill">Preview available</span>';return `<article class="lesson-row"><span class="number">${String(l.index).padStart(2,'0')}</span><a href="#lesson/${l.id}/video"><img src="${thumb(l)}" loading="lazy" alt="${esc(l.title)} video preview"></a><div class="info"><h3><a href="#lesson/${l.id}/video">${esc(l.title)}</a></h3><p>${l.course} · ${Math.ceil(l.duration_seconds/60)} min · 6 homework problems</p></div><div class="row-actions">${status}<a class="button secondary small" href="#lesson/${l.id}/video">${progress.unlocked[l.id]?'Open lesson':'Preview'} →</a></div></article>`}
function library(id){const u=id?unit(id):null,ls=u?u.lessons:Object.values(lessonMap),p=u?palette[u.id]:null;return `<div class="intro"><div><div class="eyebrow">${u?'LEVEL '+u.id.toUpperCase():'YOUR VIDEO & LESSON LIBRARY'}</div><h1>${u?u.title:'All lessons, one place'}</h1><p>${u?p.description:'Narrated videos, hands-on exploration, homework, and a check for every lesson.'}</p></div>${u?`<span class="pill">${count(u)} / ${u.lessons.length} checks passed</span>`:''}</div><div class="tabs"><a class="tab ${!id?'active':''}" href="#library">All courses</a>${catalog.units.map(c=>`<a class="tab ${id===c.id?'active':''}" href="#course/${c.id}">${c.title}</a>`).join('')}</div><div class="lesson-list">${ls.map(row).join('')}</div>${u?`<div class="tip"><div><strong>Finish with a cumulative check.</strong><br>${u.test_items_per_form} questions, delivered three at a time. Pass the lesson checks first.</div><button class="button secondary small" style="margin-left:auto;white-space:nowrap" data-unit-test="${u.id}">Unit test →</button></div>`:''}`}
function outline(l){return `<aside class="card lesson-sidebar"><div class="eyebrow">LEVEL ${l.unit.toUpperCase()}</div><h3>${l.course}</h3><div class="outline">${unit(l.unit).lessons.map(x=>`<a class="${x.id===l.id?'current':''}" href="#lesson/${x.id}/video"><span>${passed(x.id)?'✓':x.index}</span>${esc(x.title)}</a>`).join('')}</div></aside>`}
function lessonHeader(l,tab){return `<div class="intro"><div><div class="eyebrow">${l.course} · LESSON ${l.index} OF ${l.total}</div><h1>${esc(l.title)}</h1></div>${passed(l.id)?'<span class="pill done">✓ Check passed</span>':''}</div><div class="tabs" aria-label="Lesson activities">${[['video','Watch'],['explore','Explore'],['practice','Practice'],['homework','Homework'],['check','Lesson check']].map(([k,s])=>`<a class="tab ${tab===k?'active':''}" href="#lesson/${l.id}/${k}">${s}</a>`).join('')}</div>`}
function renderLesson(l,tab){
 let content='';
 if(tab==='video')content=`${l.video_available===false?'<div class="tip">The source download includes this transcript and exercises. Use the full offline bundle to watch the narrated video.</div>':`<div class="video-panel"><video id="lesson-video" controls playsinline preload="metadata" poster="${thumb(l)}" src="/${l.video_path}/final.mp4"></video></div>`}<p class="lesson-description">${esc(l.objective)}</p><details class="transcript"><summary>Read the transcript</summary>${esc(l.transcript.replace(/phase_\d\n/g,''))}</details><div class="lesson-actions"><a class="button" href="#lesson/${l.id}/explore">Explore the idea →</a><a class="button secondary" href="#lesson/${l.id}/homework">Open homework</a>${({'5-03':'algebra-2.rational-functions','5-04':'algebra-2.radicals'})[l.id]?`<a class="button secondary" href="#topic/${({'5-03':'algebra-2.rational-functions','5-04':'algebra-2.radicals'})[l.id]}">Step-by-step study guide</a>`:''}</div>`;
 if(tab==='explore')content=`<div id="embedded-lab"></div><div class="lesson-actions"><a class="button" href="#lesson/${l.id}/practice">Try three problems →</a></div><p class="lesson-description">This related exploration helps you investigate the lesson’s ideas. Use the video and homework for the full topic.</p>`;
 if(tab==='homework')content='<div class="card activity" id="homework-panel"></div>';
 if(tab==='practice')content='<div class="card activity" id="activity-panel"><div class="loading">Preparing three practice problems…</div></div>';
 if(tab==='check'){
  if(!progress.unlocked[l.id])content=`<div class="card activity"><h2>One step at a time</h2><p class="description">Pass the previous lesson check to unlock this check. You can preview this video and explore its ideas now.</p><a class="button" href="#lesson/${l.unit.toUpperCase()}-${String(l.index-1).padStart(2,'0')}/check">Go to previous check →</a></div>`;
  else if(l.unit==='5'&&!progress.bridge_passed)content=`<div class="card activity"><h2>A quick foundation check</h2><p class="description">Function inputs and squared expressions support the Algebra II lessons. Check these three ideas first.</p><a class="button" href="#bridge">Check the foundations →</a></div>`;
  else content=`<div class="card activity" id="activity-panel"><h2>Ready to make it yours?</h2><p class="description">Three independent questions. Show that you can apply the idea and recognize when it works. Pass all three to unlock the next lesson. No time limit.</p><button class="button" id="begin-check">${passed(l.id)?'Take another check':'Begin lesson check'} →</button><p class="lesson-description">You can return to practice for hints. An already exposed question cannot earn new independent credit; further tutor review may be needed.</p></div>`;
 }
 return (tab==='check'?`<a class="backlink" href="#watch/${learning.topicForLegacy(l.id)}/practice">← Back to my lesson & three problems</a><div class="intro"><div><div class="eyebrow">INDEPENDENT CHECK</div><h1>${esc(l.title)}</h1></div></div>`:lessonHeader(l,tab))+`<div class="lesson-layout"><div class="lesson-main">${content}</div>${outline(l)}</div>`;
}
function homeworkPanel(l,batch=0){const batchVersion=++homeworkView;const panel=$('#homework-panel'),questions=l.homework[batch];panel.innerHTML=`<h2>Written homework <span class="muted">· ${batch+1} / 2</span></h2><p class="description">Try these three. Write your method as well as your answer. Your tutor reviews the reasoning; these written answers are saved, not automatically graded.</p>${questions.map((q,i)=>`<div class="question"><label class="question-title" for="hw-${i}"><span class="question-num">${i+1}</span><span>${esc(q.prompt)}</span></label><textarea class="homework-answer" id="hw-${i}" data-homework="${q.id}" placeholder="My answer and how I got there…">${esc(progress.homework[l.id]?.[q.id]||'')}</textarea></div>`).join('')}<div class="batch-footer"><button class="button secondary small" id="hw-prev" ${batch===0?'disabled':''}>← Previous three</button><span class="autosave" id="hw-saved">Saved as you work</span><button class="button secondary small" id="hw-next" ${batch===1?'disabled':''}>Next three →</button></div><div class="lesson-actions"><button class="button" id="copy-homework">Copy for tutor review ↗</button><button class="button secondary" id="homework-back-practice">Back to three problems</button></div><details class="transcript"><summary>I’m stuck — how can I get help?</summary>Open “Need a hand?” in the corner to discuss a step, or use a practice hint. Your answers stay here while you ask for help.</details>`;
 let timer;const homeworkVersion=routeVersion,homeworkProfile=boundProfileId;let revision=Math.max(Date.now(),progress.homework_revisions?.[l.id]||0);const save=async()=>{const answers={...progress.homework[l.id]};panel.querySelectorAll('[data-homework]').forEach(t=>answers[t.dataset.homework]=t.value);progress.homework[l.id]={...answers};const sentRevision=++revision;progress.homework_revisions[l.id]=sentRevision;await api('homework',{lesson_id:l.id,answers,revision:sentRevision},homeworkProfile);if(routeVersion!==homeworkVersion||batchVersion!==homeworkView||sentRevision!==progress.homework_revisions[l.id])return;if($('#hw-saved'))$('#hw-saved').textContent='✓ Saved on this computer'};
 panel.querySelectorAll('textarea').forEach(t=>t.addEventListener('input',()=>{clearTimeout(timer);$('#hw-saved').textContent='Saving…';save().catch(e=>toast(e.message))}));
 $('#homework-back-practice').onclick=()=>{const extra=$('#legacy-written-extra');if(extra)extra.open=false;$('#lesson-practice')?.scrollIntoView({block:'start'});};$('#hw-prev').onclick=async()=>{clearTimeout(timer);await save();if(routeVersion!==homeworkVersion||batchVersion!==homeworkView||!panel.isConnected)return;homeworkPanel(l,batch-1)};$('#hw-next').onclick=async()=>{clearTimeout(timer);await save();if(routeVersion!==homeworkVersion||batchVersion!==homeworkView||!panel.isConnected)return;homeworkPanel(l,batch+1)};
 $('#copy-homework').onclick=async()=>{clearTimeout(timer);await save();const msg=`Please review my ${l.id} homework and help with any gaps.\n\n`+questions.map(q=>`${q.id}: ${q.prompt}\nMy work: ${progress.homework[l.id]?.[q.id]||'(not yet answered)'}`).join('\n\n');copy(msg)};
}
async function copy(s){try{await navigator.clipboard.writeText(s);toast('Copied. Paste into the tutor conversation.')}catch{toast('Copy is unavailable here. Select your work and copy it manually.')}}
async function begin(lid,mode){const panel=$('#activity-panel'),activityVersion=routeVersion,activityProfile=boundProfileId;try{panel.innerHTML='<div class="loading">Preparing your questions…</div>';const prepared=await api('activity',{lesson_id:lid,mode},activityProfile);if(activityVersion!==routeVersion||!panel.isConnected)return;currentActivity={...prepared,profileId:activityProfile};activityBatch=0;renderActivity()}catch(e){panel.innerHTML=`<div class="error">${esc(e.message)}</div><div class="lesson-actions"><a class="button secondary" href="#home">Back to dashboard</a></div>`}}
function collect(){if(!currentActivity)return;$('#activity-panel').querySelectorAll('[data-answer]').forEach(i=>{if(i.type!=='radio'||i.checked)currentActivity.answers[i.dataset.answer]=i.value})}
async function saveDraft(){collect();const s=currentActivity;s.draft_revision=(s.draft_revision||0)+1;await api('draft',{session_id:s.id,answers:{...s.answers},revision:s.draft_revision},s.profileId)}
function renderActivity(){const s=currentActivity,panel=$('#activity-panel'),activityVersion=routeVersion;if(s.submitted)return renderResults(s.result);
 const bs=Math.ceil(s.questions.length/3),items=s.questions.slice(activityBatch*3,activityBatch*3+3);panel.innerHTML=`${s.mode==='practice'&&panel.closest('.unified-lesson')?'':`<h2>${s.mode==='practice'?'Practice with feedback':s.mode==='unit'?'Unit check':'Lesson check'} <span class="muted">· set ${activityBatch+1} / ${bs}</span></h2>`}<p class="description">${s.mode==='practice'?'':'Work independently. Fractions and exact expressions are welcome. Finish all questions before submitting.'}</p>${items.map((q,i)=>`<div class="question"><div class="question-title"><span class="question-num">${activityBatch*3+i+1}</span><span id="prompt-${i}">${esc(q.prompt)}</span></div>${renderAnswerVisual(q.visual||fallbackVisual(q))}${q.kind==='choice'?`<div class="choice-grid" role="group" aria-labelledby="prompt-${i}">${q.options.map(o=>`<label class="choice"><input type="radio" name="${q.id}" data-answer="${q.id}" value="${esc(o)}" ${s.answers[q.id]===o?'checked':''}>${esc(o)}</label>`).join('')}</div>`:`<input class="answer-input" aria-labelledby="prompt-${i}" data-answer="${q.id}" value="${esc(s.answers[q.id]||'')}" placeholder="Your answer" autocomplete="off">`}${s.mode==='practice'?`<button class="hintbutton" data-hint="${q.id}">Give me a hint</button><div id="hint-${q.id}"></div>`:''}</div>`).join('')}<div class="batch-footer"><button class="button secondary small" id="activity-prev" ${activityBatch===0?'disabled':''}>← Previous three</button><span class="autosave" id="activity-save">Answers saved as you work</span>${activityBatch<bs-1?'<button class="button" id="activity-next">Next three →</button>':'<button class="button" id="activity-submit">'+(s.mode==='practice'?'Check my work':'Submit check')+' →</button>'}</div><div class="lesson-actions">${s.mode!=='practice'&&s.lesson_id!=='bridge'?`<a class="button ghost small" href="${s.mode==='unit'?'#course/'+s.lesson_id:'#lesson/'+s.lesson_id+'/practice'}">Return to practice</a>`:''}</div><div id="activity-error" role="alert"></div>`;
 panel.querySelectorAll('[data-answer]').forEach(i=>i.addEventListener('input',()=>{collect();saveDraft().catch(e=>toast(e.message))}));
 $('#activity-prev').onclick=async()=>{clearTimeout(saveTimer);await saveDraft();if(activityVersion!==routeVersion||!panel.isConnected||currentActivity?.id!==s.id)return;activityBatch--;renderActivity()};
 if($('#activity-next'))$('#activity-next').onclick=async()=>{clearTimeout(saveTimer);await saveDraft();if(activityVersion!==routeVersion||!panel.isConnected||currentActivity?.id!==s.id)return;activityBatch++;renderActivity()};
 panel.querySelectorAll('[data-hint]').forEach(b=>b.onclick=async()=>{try{const h=await api('hint',{session_id:s.id,question_id:b.dataset.hint});s.hints.push(b.dataset.hint);$('#hint-'+b.dataset.hint).innerHTML=`<div class="hint">${esc(h.hint)}</div>`}catch(e){toast(e.message)}});
 if($('#activity-submit'))$('#activity-submit').onclick=async()=>{try{clearTimeout(saveTimer);collect();$('#activity-submit').disabled=true;const result=await api('submit',{session_id:s.id,answers:s.answers},s.profileId);s.submitted=true;s.result=result;const updated=await api('progress');if(activityVersion!==routeVersion||!panel.isConnected||currentActivity?.id!==s.id)return;progress=updated;renderResults(result)}catch(e){if(activityVersion!==routeVersion||!panel.isConnected||currentActivity?.id!==s.id)return;$('#activity-error').innerHTML=`<div class="error" style="margin-top:14px">${esc(e.message)}</div>`;$('#activity-submit').disabled=false}};
}
function renderResults(r){const s=currentActivity,panel=$('#activity-panel'),l=lessonMap[s.lesson_id];const nextLesson=l?unit(l.unit).lessons[l.index]:null;
 const headline=s.mode==='practice'?(r.score===r.total?'A good start. Keep going.':'Let’s work through the gaps.'):(r.passed?'You’re ready for the next step.':'A little more practice will help.');
 panel.innerHTML=`<div class="result-hero"><div class="eyebrow">${s.mode==='practice'?'PRACTICE FEEDBACK':'CHECK RESULTS'}</div><h2>${headline}</h2><p>${r.score} of ${r.total} correct${s.mode!=='practice'?` · ${r.independent_score} independent`:''}. ${s.mode==='practice'?'Practice builds understanding; the separate lesson check unlocks the next step.':r.passed?'Your progress is saved. A later review will check retention.':'Review the specific ideas below, then try a fresh check.'}</p></div>${r.items.map((q,i)=>`<div class="question"><div class="question-title"><span class="question-num">${i+1}</span><span>${esc(q.prompt)}</span></div><p class="description">Your answer: ${esc(q.response)}</p>${renderAnswerVisual(q.visual||fallbackVisual(q,q))}<div class="feedback ${q.correct?'correct':''}"><strong>${q.correct?'✓ Correct':'Let’s revisit this idea'}${!q.independent?' · supported or previously seen':''}</strong>${esc(q.explanation)}</div></div>`).join('')}${r.needs_fresh_review?'<div class="tip">Some questions were seen before. Their correct answers count as practice, but cannot establish new independent readiness. Ask the tutor for a fresh variation if the available check bank is exhausted.</div>':''}<div class="lesson-actions">${r.passed&&s.mode==='check'?(s.lesson_id==='bridge'?'<a class="button" href="#lesson/5-01/video">Begin Algebra II →</a>':nextLesson?`<a class="button" href="#lesson/${nextLesson.id}/video">Next lesson →</a>`:`<button class="button" data-unit-test="${l.unit}">Take the unit test →</button>`):''}${s.mode==='practice'&&l?'<button class="button secondary small" id="legacy-more-practice">Try another three</button>':''}${s.mode!=='practice'&&!r.passed?'<button class="button" id="retry-activity">Try a fresh check →</button>':''}${l&&s.mode!=='practice'?`<a class="button secondary" href="#watch/${learning.topicForLegacy(l.id)}/practice">Back to my lesson</a>`:''}<button class="button secondary" id="copy-result">Ask the tutor about this</button></div>`;
 $('#legacy-more-practice')?.addEventListener('click',()=>begin(s.lesson_id,'practice'));$('#retry-activity')?.addEventListener('click',()=>begin(s.lesson_id,s.mode));$('#copy-result').onclick=()=>lessonContext?.topicId?coach.open():copy(`Please help me understand the gaps in ${s.lesson_id}. Do not count supported or repeated items as independent.\n\n`+r.items.map(q=>`${q.prompt}\nMy answer: ${q.response}\nCorrect: ${q.correct}. Independent: ${q.independent}`).join('\n\n'));wireUnitButtons();
}
function homeworkOverview(){const ls=Object.values(lessonMap).filter(l=>Object.values(progress.homework[l.id]||{}).some(v=>v.trim()));return `<div class="intro"><div><h1>Your written work</h1><p>Saved answers, ready to revisit or bring to the tutor.</p></div></div>${ls.length?`<div class="lesson-list">${ls.map(l=>`<article class="lesson-row"><img src="${thumb(l)}" alt=""/><div class="info"><h3>${l.title}</h3><p>${Object.values(progress.homework[l.id]).filter(v=>v.trim()).length} of 6 answers saved · awaiting tutor review</p></div><a class="button secondary small" href="#lesson/${l.id}/homework">Open homework →</a></article>`).join('')}</div>`:`<div class="empty-state"><h2>A space for your thinking</h2><p>Your homework will appear here as you work through the lessons.</p><a class="button" href="#lesson/4A-01/homework">Open the first three problems →</a></div>`}`}
function wireUnitButtons(){$$('[data-unit-test]').forEach(b=>b.onclick=()=>location.hash='unit-test/'+b.dataset.unitTest)}
const $$=s=>Array.from(document.querySelectorAll(s));
async function render(){const version=++routeVersion;coach.setContext(null);calculator.close();$('#open-calculator').disabled=true;disposeLab?.();disposeLab=null;videos.dispose();placement.dispose();learning.cancel();studio.cancel();mixedReview.cancel();feedbackDesk.cancel();tour.cancel();learningPath.cancel();projects.cancel();stopMathInput?.();stopMathInput=null;clearTimeout(saveTimer);const parts=(location.hash.slice(1)||'home').split('/');const [oldPage,oldId,oldTab='video']=parts;const legacyTopic=oldPage==='lesson'?learning.topicForLegacy(oldId):null;if(legacyTopic&&['video','practice','homework'].includes(oldTab)){parts.splice(0,parts.length,'watch',legacyTopic,oldTab);history.replaceState(null,'','#watch/'+legacyTopic+(oldTab==='video'?'':'/'+oldTab));}else if(oldPage==='topic'&&videos.has(oldId)&&['video','understand','practice'].includes(oldTab)){const nextTab=oldTab==='practice'?'practice':'guide';parts.splice(0,parts.length,'watch',oldId,nextTab);history.replaceState(null,'','#watch/'+oldId+'/'+nextTab);}try{[progress,learningState]=await Promise.all([api('progress'),api('learning')]);if(version!==routeVersion)return;progress.learning_support=learningState;learningPath.setState(progress,learningState);learning.setProgress(progress);learning.updateProfile();const [page,id,tab='video']=parts;setLessonTools(page,id,tab);$('#breadcrumb').textContent=page==='home'?'Home':page==='lesson'?`${lessonMap[id]?.course||'Lesson'} / ${tab}`:page==='lab'?'Math playground':page==='course'?'Courses / '+(unit(id)?.title||''):(page==='homework'?'My homework':'Lesson library');$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===({'watch':'videos','course':'videos','library':'videos','studio':'applications','missions':'applications','mission':'applications','projects':'applications','ai-math':'applications','investigations':'applications'}[page]||page)));$('#nav-more').open=false;
 if(page==='tour'){await tour.mount();}
 else if(page==='session'){$('#main').innerHTML='<div id="session-host"></div>';await learningPath.renderSession($('#session-host'),videos.next(progress));$('#breadcrumb').textContent='Daily warm-up';}
 else if(page==='ai-math'){
  const captured=boundProfileId,content=await api('ai-learning');if(version!==routeVersion)return;
  $('#main').innerHTML='<a class="backlink" href="#applications">← All fields</a><div id="ai-learning-host"></div>';$('#breadcrumb').textContent='Math behind AI';
  let revision=Math.max(Date.now(),learningState.ai_path?.revision||0),pending=Promise.resolve();
  disposeLab=mountAILearning($('#ai-learning-host'),{esc,toast,topic:id=>learning.topic(id),content,initialState:learningState.ai_path?.draft,getContext:()=>({profileId:boundProfileId,independentCheck:version!==routeVersion||captured!==boundProfileId}),onStageChange:event=>{const topicId=typeof event==='string'?event:event?.topicId;if(topicId)setLessonTools('watch',topicId,'ai-math');},onSupport:event=>api('learning/support',{topic_ids:event.topicIds||[event.topicId].filter(Boolean)},captured),onSave:(draft,options={})=>{const number=++revision,send=()=>api('learning/ai',{draft,revision:number},captured);const request=options.flush?send():(pending=pending.catch(()=>{}).then(send));return request.then(result=>{if(captured===boundProfileId&&number===revision)learningState.ai_path=result.record;return result;});}});
 }
 else if(page==='projects'){$('#main').innerHTML='<div id="project-host"></div>';projects.render($('#project-host'),id,progress,learningState);$('#breadcrumb').textContent='Connected projects';}
 else if(page==='pilot'){$('#main').innerHTML='<div id="pilot-host"></div>';learningPath.renderPilot($('#pilot-host'));$('#breadcrumb').textContent='Learner pilot';}
 else if(page==='review'){await mixedReview.mount(id);}
 else if(page==='feedback'){await feedbackDesk.mount(id,tab);}
 else if(page==='applications'||page==='studio'&&!id){
  const captured=boundProfileId,content=await api('purpose-paths');if(version!==routeVersion)return;
  $('#breadcrumb').textContent='Apply the math';$('#main').innerHTML='<div id="purpose-host"></div>'+(id?'':'<div class="applications-secondary"><a href="#missions">Explore all lesson activities →</a><a href="#investigations">More investigations →</a></div>');
  let revision=Math.max(Date.now(),learningState.purpose_paths?.[id]?.revision||0),pending=Promise.resolve();
  disposeLab=mountPurposePaths($('#purpose-host'),{content,fieldId:id,esc,topic:tid=>learning.topic(tid),initialDraft:learningState.purpose_paths?.[id]?.draft,getContext:()=>({profile_id:boundProfileId,independentCheck:version!==routeVersion||captured!==boundProfileId}),onSupport:event=>api('learning/support',{topic_ids:Array.isArray(event)?event:event.topicIds||[]},captured),onStageChange:event=>{if(event.topicIds?.[0])setLessonTools('watch',event.topicIds[0],'application');},onError:error=>toast(error.message||String(error)),onDraft:(draft,options={})=>{if(!id)return Promise.resolve();const number=++revision,send=()=>api('learning/purpose',{field_id:id,draft,revision:number},captured);const request=options.flush?send():(pending=pending.catch(()=>{}).then(send));return request.then(result=>{if(captured===boundProfileId&&number===revision){learningState.purpose_paths??={};learningState.purpose_paths[id]=result.record;}return result;});}});
 }
 else if(page==='missions'){$('#breadcrumb').textContent='Lesson activities';$('#main').innerHTML='<a class="backlink" href="#applications">← All fields</a><div id="mission-directory"></div>';disposeLab=mountMissionDirectory($('#mission-directory'),{esc,api,content:missionContent});}
 else if(page==='studio'||page==='tailor'||page==='investigations'){await studio.mount(id,tab,page==='tailor');if(version!==routeVersion)return;$('#main').insertAdjacentHTML('afterbegin','<a class="backlink" href="#applications">← All fields</a>');}
 else if(page==='mission'){$('#main').innerHTML='<div class="focused-lesson-return"><a href="#missions">← All lesson activities</a><a href="#watch/'+encodeURIComponent(id)+'">Open this lesson & practice →</a></div><div id="standalone-mission"></div>';disposeLab=mountLessonMission($('#standalone-mission'),id);$('#breadcrumb').textContent='Apply the math';}
 else if(page==='placement'){await placement.mount();}
 else if(await videos.render(page,id,tab,progress)){}
 else if(await learning.render(page,id,tab,progress)){if(version!==routeVersion)return;if(page==='progress'){const detail=document.createElement('details');detail.className='progress-details';detail.innerHTML='<summary class="progress-detail-summary">My saved checks, explanations & review schedule</summary>'+$('#main').innerHTML;$('#main').innerHTML='<div id="skill-tree-host"></div>';$('#main').append(detail);disposeLab=mountSkillTree($('#skill-tree-host'),{courses:learning.courses(),progress,esc});await studio.refreshState();if(version!==routeVersion)return;detail.insertAdjacentHTML('beforeend',studio.reviewSummary());await mixedReview.refresh();if(version!==routeVersion)return;detail.insertAdjacentHTML('beforeend',mixedReview.progressCard());}if(page==='about')$('#main').insertAdjacentHTML('beforeend','<p class="pilot-entry"><a href="#pilot">Help test how well Catalyst supports learning →</a></p>');if(page==='topic'&&tab!=='check')$('#main').insertAdjacentHTML('beforeend',studio.related(id));}
 else if(page==='home')$('#main').innerHTML=home()+purposePathCard();
 else if(page==='reasoning'){$('#breadcrumb').textContent='Why this step?';$('#main').innerHTML='<div id="reasoning-host"></div>';const notified=new Set();disposeLab=mountReasoning($('#reasoning-host'),{path:id,onEvent:event=>{for(const topicId of event.topicIds||[event.topicId])if(topicId&&!notified.has(topicId)){notified.add(topicId);api('topic/help',{topic_id:topicId}).catch(e=>toast(e.message));}}});}
 else if(page==='library'||page==='course')$('#main').innerHTML=library(page==='course'?id:null);
 else if(page==='homework'){await studio.refreshState();if(version!==routeVersion)return;const extraWork=videos.homework(progress)+learning.homeworkExtras()+studio.savedWork()+missionHomework()+purposeHomework()+learningPath.notebookLinks()+(learningState.ai_path?'<section class="saved-learning-notes"><h2>My AI experiment</h2><a href="#ai-math">Continue my saved model, calculations and notes →</a></section>':'');$('#main').innerHTML=homeworkOverview()+extraWork;if(extraWork)$('#main .empty-state')?.remove();$('#main .intro').insertAdjacentHTML('afterend','<div class="lesson-actions"><a class="button secondary" href="#feedback">Review and improve my reasoning →</a><a class="button secondary" href="#review">Practice a fresh mixed set →</a></div>');}
 else if(page==='lab'){$('#main').innerHTML='<div id="playground-host"></div>';disposeLab=mountPlayground($('#playground-host'),{tool:id,family:tab,esc,onCopy:copy,onSupport:topicIds=>{for(const topicId of topicIds)api('topic/help',{topic_id:topicId}).catch(e=>toast(e.message));}});}
 else if(page==='lesson'&&lessonMap[id]){const l=lessonMap[id];if(['video','homework','explore'].includes(tab)){const tid=learning.topicForLegacy(id);if(tid)api('topic/help',{topic_id:tid}).catch(e=>toast(e.message));}$('#main').innerHTML=renderLesson(l,tab);if(['video','homework','explore'].includes(tab))$('#main .tabs')?.insertAdjacentHTML('afterend',studio.relatedLegacy(id));if(tab==='explore')disposeLab=mountLab($('#embedded-lab'),labFor(l.slug),l.slug);if(tab==='homework')homeworkPanel(l);if(tab==='practice')await begin(id,'practice');if(tab==='check'&&$('#begin-check'))$('#begin-check').onclick=()=>begin(id,'check');
  const v=$('#lesson-video');if(v){v.addEventListener('loadedmetadata',()=>{const t=progress.lessons[id]?.video_seconds||0;if(t>2&&t<v.duration-3)v.currentTime=t});let last=0;v.addEventListener('timeupdate',()=>{if(v.currentTime-last>8){last=v.currentTime;api('video',{lesson_id:id,seconds:v.currentTime}).catch(()=>{})}});v.addEventListener('ended',()=>api('video',{lesson_id:id,seconds:v.duration}).catch(()=>{}))}}
 else if(page==='bridge'){$('#main').innerHTML='<div class="intro"><div><div class="eyebrow">BEFORE ALGEBRA II</div><h1>Check the foundations</h1><p>Three focused questions about function inputs and squared expressions.</p></div></div><div class="card activity" id="activity-panel"></div>';await begin('bridge','check')}
 else if(page==='unit-test'&&unit(id)){$('#main').innerHTML=`<div class="intro"><div><div class="eyebrow">LEVEL ${id.toUpperCase()} · CUMULATIVE CHECK</div><h1>${unit(id).title}</h1><p>80% independent success, with at least one correct independent item from every lesson.</p></div></div><div class="card activity" id="activity-panel"></div>`;await begin(id,'unit')}
 else{$('#main').innerHTML='<div class="error">That lesson could not be found. <a href="#home">Return to the dashboard.</a></div>'}
 if(version!==routeVersion)return;$('#open-calculator').disabled=false;wireUnitButtons();stopMathInput=watchMathInputs();if(!(page==='watch'&&['practice','homework','guide','steps'].includes(tab)))window.scrollTo({top:0});}catch(e){if(version!==routeVersion)return;$('#main').innerHTML=`<div class="error">${esc(e.message)}<p>Keep the local Catalyst server running, then reload this page.</p></div>`}}
function watchMathInputs(){const profile=boundProfileId,disposers=[],seen=new WeakSet();const add=root=>{disposers.push(enhanceMathInputs(root,{selector:'input.answer-input,textarea.homework-answer',filter:input=>{if(seen.has(input))return false;seen.add(input);return true;},esc,getContext:()=>lessonContext||{profileId:profile},onSupport:event=>api('calculator/support',{topic_id:lessonContext?.topicId||null,kind:event.kind},profile)}));};add($('#main'));const observer=new MutationObserver(records=>{if(records.some(r=>Array.from(r.addedNodes).some(n=>n.nodeType===1&&!n.classList.contains('math-input-helper'))))add($('#main'));});observer.observe($('#main'),{childList:true,subtree:true});return()=>{observer.disconnect();for(const stop of disposers)stop?.();};}
$('.skip').addEventListener('click',event=>{event.preventDefault();$('#main').focus();$('#main').scrollIntoView({block:'start'});});
$('#open-calculator').onclick=openCalculator;
$('#export').onclick=async()=>{try{const data=await api('export'),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='catalyst-progress.json';a.click();URL.revokeObjectURL(url)}catch(e){toast(e.message)}};
try{catalog=await api('catalog');catalog.units.forEach(u=>u.lessons.forEach(l=>lessonMap[l.id]=l));await learning.load();await videos.load();await studio.load();await projects.load();missionContent=await loadMissionContent(api).catch(()=>null);window.addEventListener('hashchange',render);await render()}catch(e){$('#main').innerHTML=`<div class="error">${esc(e.message)}<p>Open Catalyst using its local server, not by double-clicking this HTML file.</p></div>`}

document.addEventListener('click',e=>{const menu=$('#nav-more');if(menu.open&&!menu.contains(e.target))menu.open=false;});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#nav-more').open){$('#nav-more').open=false;$('#nav-more summary').focus();}});
